name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/tamimystic/Impact-of-Ai-on-Students
          git push --force https://tamimystic:$HF_TOKEN@huggingface.co/spaces/tamimystic/Impact-of-Ai-on-Students main
